// WITH_RUNTIME
class FooException : Exception()

@Throws(FooException::class)
fun test() {
    throw FooException()
}